# Generated by Django 3.0.3 on 2020-12-27 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOBILE_NUMBER', models.CharField(max_length=12)),
                ('FIRST_NAME', models.CharField(max_length=30)),
                ('LAST_NAME', models.CharField(max_length=30)),
                ('ID_TYPE', models.CharField(choices=[('1', 'Work ID'), ('2', 'Student ID')], max_length=10)),
                ('ID_NUMBER', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, null=True)),
                ('DOB', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
            ],
            options={
                'verbose_name': 'CUSTOMER',
                'verbose_name_plural': 'CUSTOMERS',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='REGISTER.Country')),
            ],
            options={
                'verbose_name': 'STATE',
                'verbose_name_plural': 'STATES',
            },
        ),
    ]
